# Generated by Django 5.1.3 on 2024-11-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('biography', models.TextField(max_length=999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
